#!/usr/bin/env python3
"""
check-doc-counts.py: keep the human-facing corpus numbers honest.

The machine truth is manifest.json (regenerated by build-manifest.py,
freshness-checked in CI). The human-facing docs repeat those numbers in
prose: README.md (headline, overview table, coverage matrix), CORPUS.md
(header, inventory line), CITATION.cff (title, abstract) and .zenodo.json
(the archival deposit description, which becomes the DOI landing page and
cannot be edited by a later commit). History shows they drift when a book
or locale lands; this gate makes the drift loud.

Checks:

1. Headline counts. Every "N books" / "N individual works" /
   "N markdown files" / "N locales" / "N languages" /
   "N language families" phrase in any of those docs must match the
   values derived from manifest.json (books = bookCount, locales =
   localeCount, languages = distinct primary BCP-47 subtags, families =
   distinct top-level family labels in the README coverage matrix).
2. The "N beyond modern English" parenthetical in CORPUS.md
   (locales minus the en-* variants minus the historical stages ang
   and enm).
3. Coverage-matrix integrity. Every corpus locale appears in exactly
   one row of the README coverage matrix, no row names a locale that
   is not in the corpus, and each row's book count matches the
   manifest.

Usage:
  python3 scripts/check-doc-counts.py            # verify, exit 1 on drift
  python3 scripts/check-doc-counts.py --explain  # also print the derivations

Exit codes: 0 clean, 1 drift found, 2 IO/parse error.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Phrases whose leading integer must equal the named quantity.
# \s+ between words so YAML line-wrapping (CITATION.cff) still matches.
PHRASE_QUANTITIES = [
    (re.compile(r'(\d+)\s+languages\b'), 'languages'),
    (re.compile(r'(\d+)\s+locales\b'), 'locales'),
    (re.compile(r'(\d+)\s+books\b'), 'books'),
    (re.compile(r'(\d+)\s+individual\s+works\b'), 'books'),
    (re.compile(r'(\d+)\s+markdown\s+files\b'), 'books'),
    (re.compile(r'(\d+)\s+language\s+families\b'), 'families'),
    (re.compile(r'(\d+)\s+beyond\s+modern\s+English\b'), 'beyond_english'),
]

DOCS = ['README.md', 'CORPUS.md', 'CITATION.cff', '.zenodo.json']


def derive_counts():
    manifest = json.loads((REPO_ROOT / 'manifest.json').read_text())
    locales = set(manifest['locales'])
    languages = {loc.split('-')[0] for loc in locales}
    english = {loc for loc in locales if loc.split('-')[0] == 'en'} | {'ang', 'enm'}
    per_locale = {}
    for book in manifest['books']:
        per_locale[book['locale']] = per_locale.get(book['locale'], 0) + 1
    return {
        'books': manifest['bookCount'],
        'locales': manifest['localeCount'],
        'languages': len(languages),
        'beyond_english': manifest['localeCount'] - len(english & locales),
        'per_locale': per_locale,
        'locale_set': locales,
    }


def parse_coverage_matrix(readme_text):
    """Rows of the README coverage matrix as (family, locales, count)."""
    section = readme_text.split('## Coverage matrix', 1)
    if len(section) < 2:
        return None
    rows = []
    for line in section[1].splitlines():
        line = line.strip()
        if rows and not line.startswith('|'):
            break
        m = re.match(r'\|([^|]+)\|[^|]+\|([^|]+)\|\s*(\d+)\s*\|$', line)
        if not m:
            continue
        family = m.group(1).strip()
        if family in ('Family', '---'):
            continue
        locales = [t.strip() for t in m.group(2).split(',') if t.strip()]
        rows.append((family, locales, int(m.group(3))))
    return rows


def main():
    explain = '--explain' in sys.argv[1:]
    try:
        counts = derive_counts()
    except (OSError, json.JSONDecodeError, KeyError) as err:
        print(f'check-doc-counts: cannot derive counts from manifest.json: {err}')
        return 2

    readme = (REPO_ROOT / 'README.md').read_text()
    rows = parse_coverage_matrix(readme)
    problems = []

    if rows is None or not rows:
        problems.append('README.md: coverage matrix not found or empty')
        counts['families'] = -1
    else:
        counts['families'] = len({family.split(',')[0].strip() for family, _, _ in rows})
        seen = {}
        for family, locales, claimed in rows:
            actual = 0
            for loc in locales:
                if loc not in counts['locale_set']:
                    problems.append(
                        f'README.md coverage matrix: row "{family}" names locale '
                        f'{loc!r} which is not in the corpus')
                    continue
                if loc in seen:
                    problems.append(
                        f'README.md coverage matrix: locale {loc!r} appears in both '
                        f'"{seen[loc]}" and "{family}"')
                seen[loc] = family
                actual += counts['per_locale'][loc]
            if actual != claimed:
                problems.append(
                    f'README.md coverage matrix: row "{family}" claims {claimed} '
                    f'book(s) but its locales hold {actual}')
        missing = counts['locale_set'] - set(seen)
        for loc in sorted(missing):
            problems.append(f'README.md coverage matrix: corpus locale {loc!r} is in no row')

    if explain:
        print('derived: ' + ', '.join(
            f'{key}={counts[key]}' for key in
            ('books', 'locales', 'languages', 'families', 'beyond_english')))

    for name in DOCS:
        text = (REPO_ROOT / name).read_text()
        for pattern, quantity in PHRASE_QUANTITIES:
            for m in pattern.finditer(text):
                stated = int(m.group(1))
                expected = counts[quantity]
                if stated != expected:
                    line = text[:m.start()].count('\n') + 1
                    problems.append(
                        f'{name}:{line}: says "{m.group(0)}" but the corpus has '
                        f'{expected} ({quantity})')

    if problems:
        for p in problems:
            print(p)
        print(f'check-doc-counts: {len(problems)} problem(s)')
        return 1
    print('check-doc-counts: all stated counts match the manifest')
    return 0


if __name__ == '__main__':
    sys.exit(main())
